# Generated by Django 4.2 on 2023-04-22 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='student',
            name='hostel',
        ),
        migrations.DeleteModel(
            name='Hostel',
        ),
    ]
