# Generated by Django 4.2 on 2023-05-02 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_attendance_attendance_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance_report',
            name='present',
            field=models.BooleanField(default=False),
        ),
    ]
