# Generated by Django 4.2 on 2023-05-02 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_attendance_report_present'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=10)),
                ('breakfast', models.TextField(max_length=100)),
                ('lunch', models.TextField(max_length=100)),
                ('dinner', models.TextField(max_length=100)),
            ],
        ),
    ]
