# Generated by Django 4.1.7 on 2023-05-04 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_mess'),
    ]

    operations = [
        migrations.AddField(
            model_name='mess_off_leave',
            name='days',
            field=models.IntegerField(default=0),
        ),
    ]
