# Generated by Django 4.2 on 2023-05-04 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_remove_mess_off_leave_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mess_off_leave',
            name='off_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='mess_off_leave',
            name='on_date',
            field=models.DateField(),
        ),
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=10)),
                ('year', models.IntegerField()),
                ('days_of_leave_taken', models.PositiveIntegerField(default=0)),
                ('total_days_in_month', models.IntegerField()),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=6)),
                ('payment_status', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.student')),
            ],
        ),
    ]
