# Generated by Django 4.1.7 on 2023-05-07 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_mess_off_leave_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff_leave',
            name='days',
            field=models.IntegerField(default=0),
        ),
    ]
